### ISSUE TITLE
Higher-Kinded Types

### ISSUE THREAD

**Issue by stereobooster** [minoki/purescript-tsd-gen#1]
One way to do HKT is https://gist.github.com/gcanti/2b455c5008c2e1674ab3e8d5790cdad5#file-fp-ts-technical-overview-md

**Comment by sledorze** [comment]
There have been several iterations in `fp-ts` library.
I would advise you to check it.
https://github.com/gcanti/fp-ts/blob/master/src/HKT.ts

Also, its creator takes Purescript as the example to follow, so it may help a lot!
