### ISSUE TITLE
Replace single quotes in type names with a valid character for TS 

### ISSUE THREAD

**Issue by sharno** [minoki/purescript-tsd-gen#5]
As single quote `'` is a valid character in PS for type names, and it is invalid for TS. I think replacing the single quote with some other valid character is needed?
Examples of such types are in https://pursuit.purescript.org/packages/purescript-profunctor-lenses/3.2.0/docs/Data.Lens.Types

Not sure though which character is the best to replace it

Edit:
I have 2 proposed solutions:
1. Deal with it like Purescript itself converting any `'` to `$prime`

2. Replace it with a valid unicode. I found 2 unicode characters that would represent the single quote in TS in variable/type names while being considered the same as single quote in PS (so would throw a duplicate name error at compile time if used along with the single quote):
    - [Modified Letter Prime](https://www.compart.com/en/unicode/U+02B9): `ʹ`
    - [Modified Letter Apostrophe](https://www.compart.com/en/unicode/U+02BC): `ʼ`

    Try it in TS: https://www.typescriptlang.org/play/#code/C4TwDgpgBAgonUBQLxQN4EMBcUDOwBOAlgHYDmAvgNxQD01UYhAthALABQ7okUAQoD1ASVFEw58xElEo06aMAHtceOWAAWrNkA

**Comment by minoki** [comment]
Thanks for the report! I'll take a look at it.
